### ISSUE TITLE
ttyname_hack is broken

### ISSUE THREAD

**Issue by Duncaen** [multiplexd/doas#1]
This might avoid a bug they had in parsing `/proc/self/stat`, but Its vulnerable to an even older issue https://www.sudo.ws/alerts/tty_tickets.html.
`stdin`, `stdout` and `stderr` are user controllable, you could run doas with a terminal from another session attached to them and then hijack a timestamp from a local tty from e.g. a pseudo terminal from inside a ssh session.

**Comment by multiplexd** [comment]
The timestamp records the username, controlling terminal attached to file descriptors 0, 1 or 2 and the **parent process ID**. I have read through the sudo advisory you linked to, and as far as my understanding goes, the vulnerability in sudo existed because they tracked the session ID of the sudo process (which is important in the context of TTY semantics. doas only records (both on OpenBSD and here) its parent process ID (see [this thread](https://marc.info/?l=openbsd-misc&m=150028661715881&w=2) for some background), so the authentication token is tied to a specific shell process (assuming interactive use; under a script it would be the script process). 

As I understand it, the attack you describe would fail because although it is possible to run doas from another terminal with the appropriate file descriptors redirected, the parent process ID of doas would be different from the shell running under the TTY you wish to use.

**Comment by Duncaen** [comment]
The session ID is in many cases the parent process ID, this doesn't add entropy.
Yes it sounds a bit complicated to exploit but doable.
Opening the other tty/pty, killing the other terminal, forking in a loop until you hit the right ppid.

**Comment by multiplexd** [comment]
Okay, I think I understand. Any suggestions on how to fix this?

**Comment by Duncaen** [comment]
I think parsing `/proc/self/stat` is the only way to go.
You just need to make sure to parse 5 fields after the last `)` to avoid the other exploit.
This is still a bit flaky, I'm still trying to find more data to include into the timestamp, because I don't think the ppid/sid/tty combination is very secure, even if its the real controlling terminal it could be possible to kill the process and then trying get the same terminal again and then trying to get the right ppid.
Maybe using the start time of the parent process would help, the time could be compared to the timestamps too.
If the start time of the parent process is >= the time in the timestamp there is definitively something wrong.

**Comment by multiplexd** [comment]
Commit 9901df5 attempts to address this issue by additionally recording the parent process's process group ID and doas's session ID. I'll leave this issue open, pending further discussion.

**Comment by multiplexd** [comment]
I've rewritten the persistence token code in a feature branch to track session lifetime. Could you take a look at it?

**Comment by multiplexd** [comment]
Closed following conversation on IRC
